galerias/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('galerias.views',
    url(r'^$', 'albuns', name='albuns'),
    url(r'^(?P<slug>[\w_-]+)/$', 'album', name='album'),
    url(r'^imagem/(?P<slug>[\w_-]+)/$', 'imagem', name='imagem'),
)

meu_blog/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from blog.feeds import UltimosArtigos

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'blog.views.Artigos', name='home'),
    url(r'^galeria/', include('galerias.urls')),
    url(r'^tags/', include('tags.urls')),
    # url(r'^meu_blog/', include('meu_blog.foo.urls')),
    url(r'^contato/$', 'meu_blog.views.contato', name='contato'),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^meu_blog/$', 'blog.views.Artigos', name="blog_gustavo"),
    url(r'^artigo/(?P<slug>[\w_-]+)/$', 'blog.views.MostraArtigo', name="artigo"),
    url(r'^comments/', include('django.contrib.comments.urls'), name="comentarios"),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^rss/ultimos/$', UltimosArtigos())
)

tags/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('tags.views',
    url(r'^$', 'tags', name='tags'),
    url(r'^(?P<tag_nome>.*?)/$', 'tag', name='tag'),
)

blog/models.py
from django.core.urlresolvers import reverse
from datetime import datetime
from django.db import models
from django.db.models import signals
from meu_blog.utils import slug_pre_save

class Artigo(models.Model):
    titulo = models.CharField(max_length=100)
    conteudo = models.TextField()
    publicacao = models.DateTimeField(default=datetime.now, blank=True)
    slug = models.SlugField(max_length=100, blank=True, unique=True)

    class Meta:
        ordering = ('-publicacao',)

    def get_absolute_url(self):
        return reverse('artigo', kwargs={'slug': self.slug})

    def __unicode__(self):
        return self.titulo

# SIGNALS

signals.pre_save.connect(slug_pre_save, sender=Artigo)

galerias/models.py
from datetime import datetime
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models import signals
from meu_blog.utils import slug_pre_save

class Album(models.Model):
    """Um album eh um pacote de imagens, ele tem um titulo e um slug para sua
    identificacao."""
    class Meta:
        ordering = ('titulo',)

    titulo = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, blank=True, unique=True)

    def __unicode__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('galerias.views.album', args=[str(self.slug)])

class Imagem(models.Model):
    """Cada instancia desta classe contem uma imagem da galeria, com seu
    respectivo thumbnail (miniatura) e imagem em tamanho natural.
    Varias imagens podem conter dentro de um Album"""

    class Meta:
        ordering = ('album','titulo',)

    album = models.ForeignKey('Album')
    titulo = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, blank=True, unique=True)
    descricao = models.TextField(blank=True)
    original = models.ImageField(
        null=True,
        blank=True,
        upload_to='galeria/original',
    )
    thumbnail = models.ImageField(
        null=True,
        blank=True,
        upload_to='galeria/thumbnail',
    )
    publicacao = models.DateTimeField(default=datetime.now, blank=True)

    def __unicode__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('imagem', kwargs={'slug': self.slug})
# SIGNALS
signals.pre_save.connect(slug_pre_save, sender=Album)
signals.pre_save.connect(slug_pre_save, sender=Imagem)

tags/models.py
from django.db import models
from django.contrib. contenttypes.models import ContentType
from django.contrib.contenttypes.generic import GenericForeignKey
from django.core.urlresolvers import reverse

class Tag(models.Model):
    nome = models.CharField(max_length=30, unique=True)

    def get_absolute_url(self):
            return reverse('tag', kwargs={'tag_nome': self.nome})


    def __unicode__(self):
        return self.nome

class TagItem(models.Model):
    class Meta:
        unique_together = ('tag', 'content_type', 'object_id')

    tag = models.ForeignKey('Tag')
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField(db_index=True)
    objeto = GenericForeignKey('content_type', 'object_id')

meu_blog/forms.py
from django import forms
from django.core.mail import send_mail

class FormContato(forms.Form):
    nome = forms.CharField(max_length=50)
    email = forms.EmailField(required=False)
    mensagem = forms.CharField(widget=forms.Textarea)

    def enviar(self):
        titulo = 'Mensagem enviada pelo site'
        destino = 'gustavo_bisetti@hotmail.com'
        texto = """
        Nome: %(nome)s
        E-mail: %(email)s
        Mensagem:
        %(mensagem)s
        """ % self.cleaned_data

        send_mail(
            subject=titulo,
            message=texto,
            from_email=destino,
            recipient_list=[destino],
            )

blog/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.core.urlresolvers import reverse
from .models import Artigo
from django.template import RequestContext
from django.shortcuts import get_object_or_404

def Artigos(request):
    queryset=Artigo.objects.all()
    return render_to_response('blog/artigo_arquive.html', RequestContext(
        request,
        {'Artigos': queryset}
    ))

def MostraArtigo(request, slug):
    return render_to_response('blog/artigo.html', RequestContext(
        request,
        {'artigo': get_object_or_404(Artigo, slug=slug)}
    ))

galerias/views.py
from django.shortcuts import get_object_or_404, render

from models import Album, Imagem

def albuns(request):
    return render(
        request,
        'galerias/albuns.html',
        {'lista': Album.objects.all()}
    )

def album(request, slug):
    album_ = get_object_or_404(Album, slug=slug)
    return render(
        request,
        'galerias/album.html',
        {
            'album': album_,
            'imagens': Imagem.objects.filter(album=album_)
        }
    )

def imagem(request, slug):
    imagem_ = get_object_or_404(Imagem, slug=slug)
    return render(
        request,
        'galerias/imagem.html',
        {
            'imagem': imagem_
        }
    )

meu_blog/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from .forms import FormContato

def contato(request):
    mostrar = ''
    if request.method == 'POST':
        form = FormContato(request.POST)

        if form.is_valid():
            form.enviar()
            mostrar = 'Contato enviado!'
    else:
        form = FormContato()


    return render_to_response(
        'contato.html', RequestContext(
        request, {'form': form,'mostrar': mostrar})
    )

tags/views.py
from django.shortcuts import render, get_object_or_404
from django.template import RequestContext

from .models import Tag

def tags(request):
    return render(request,
        'tags/tags.html',
        {'lista': Tag.objects.all(),}
    )

def tag(request, tag_nome):
    return render(request,
        'tags/tag.html',
        {'tag': get_object_or_404(Tag, nome=tag_nome)}
    )

blog/templates/blog/artigo.html
{% extends "base.html" %}

{% load comments %}

{% block titulo %}{{ artigo.titulo }} - {{ block.super }}{% endblock %}

{% block h1 %}{{ artigo.titulo }}{% endblock %}

{% block conteudo %}

{% with artigo as objeto %}
{% include "tags/tags_para_objeto.html" %}
{% endwith %}

{{ artigo.conteudo }}


<div class="comentarios">
  <h3>Comentarios</h3>

  {% get_comment_list for artigo as comentarios %}
  {% for comentario in comentarios %}
  <div class="comentario">
    Nome: {{ comentario.name }}<br/>
    {% if comentario.url %}URL: {{ comentario.url }}{% endif %}<br/>
    {{ comentario.comment|linebreaks }}
    <hr/>
  </div>
  {% endfor %}

  <h3>Envie um comentário</h3>

  {% render_comment_form for artigo %}
</div>


{% endblock %}

blog/templates/blog/artigo_arquive.html
{% extends "base.html" %}

{% block conteudo %}
<img src="{{ STATIC_URL }}foto.jpg" />
{% for artigo in Artigos %}
  <div class="artigo">
    <a href="{{ artigo.get_absolute_url }}"><h2>{{ artigo.titulo }}</h2></a> 

    <div class="conteudo">
      Publicado há {{ artigo.publicacao|timesince }}<br/>
      {{ artigo.conteudo }}
    </div>
  </div>
{% endfor %}
{% endblock %}

blog/templates/feeds/ultimos_description.html
{{ obj.conteudo }}

blog/templates/feeds/ultimos_title.html
{{ obj.titulo }}

galerias/templates/galerias/album.html
{% extends "base.html" %}

{% block titulo %}{{ album }} - {{ block.super }}{% endblock %}

{% block h1 %}{{ album }}{% endblock %}

{% block conteudo %}
<div class="miniaturas">

    {% for imagem in imagens %}
    <div class="miniatura">
        <a href="{{ imagem.get_absolute_url }}">
        <img src="{{ imagem.thumbnail.url }}"/>
        {{ imagem }}
        </a>
    </div>
    {% endfor %}
</div>
{% endblock conteudo %}

galerias/templates/galerias/albuns.html
{% extends "base.html" %}

{% block titulo %}Galeria de Imagens - {{ block.super }}{% endblock %}

{% block h1 %}Galeria de imagens{% endblock %}

{% block conteudo %}

<ul>
    {% for album in lista %}
    <li><a href="{{ album.get_absolute_url }}">{{ album }}</a></li>
    {% endfor %}
</ul>

{% endblock conteudo %}

galerias/templates/galerias/imagem.html
{% extends "base.html" %}

{% block titulo %}{{ imagem }} - {{ block.super }}{% endblock %}

{% block h1 %}{{ imagem }}{% endblock %}

{% block conteudo %}
<div class="imagem">
    <img src="{{ imagem.original.url }}"/>

    {{ imagem.descricao|linebreaks }}
    {% with imagem as objeto %}
    {% include "tags/tags_para_objeto.html" %}
    {% endwith %}

</div>
{% endblock conteudo %}

meu_blog/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-br" lang="pt-br">
 <head>
  <title>{% block titulo %}Blog do Gustavo{% endblock %}</title>

  {% block meta %}
  <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Language" content="pt-br" />
  <meta name="keywords" content="Python, Django, Gustavo, Piracicaba, blog" />
  <meta name="description" content="Este é o blog do Gustavo, um jovem aprendendo Django." />
  {% endblock meta %}

  {% block feeds %}
  <link rel="alternate" type="application/rss+xml" title="Ultimos artigos do Gustavo" href="/rss/ultimos/" />
  {% endblock feeds %}
  
  {% block style %}
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}layout.css"/>
  {% endblock style %}

  {% block scripts %}
  {% endblock scripts %}
</head>

<body>
 <div id="tudo">
  <div id="topo">
   {% block topo %}
   <div id="foto">&nbsp;</div>
   Blog do Gustavo
   {% endblock topo %}
  </div>

  <div id="menu">
   {% block menu %}
   {% spaceless %}
   <ul>
    <li><a href="/">Pagina inicial</a></li>
    <li><a href="{% url 'galerias.views.albuns' %}">Galeria de imagens</a></li>
    <li><a href="{% url 'tags.views.tags' %}">Tags</li>
    <li><a href="/sobre-mim/">Sobre mim</a></li>
    <li><a href="{% url 'views.contato' %}">Contato</a></li>
   </ul>
   {% endspaceless %}
   {% endblock menu %}
  </div>

  <h1>{% block h1 %}{% endblock %}</h1>

  <div class="corpo">
  {% block conteudo %}{% endblock %}
  </div>

  {% include "rodape.html" %}
 
 </div>
</body>
</html>

meu_blog/templates/comments/base.html
{% extends "base.html" %}

{% block titulo %}
  {% block title %}{% endblock %}
{% endblock %}

{% block conteudo %}
  {% block content %}{% endblock %}
{% endblock %}
  

meu_blog/templates/contato.html
{% extends "base.html" %}

{% block titulo %}Contato - {{ block.super }}{% endblock %}

{% block h1 %}Contato{% endblock %}

{% block conteudo %}
{% if mostrar %}<h3>{{ mostrar }}</h3>{% endif %}

Informe seus dados abaixo:

<form method="post"> {% csrf_token %}
  <table>
    {{ form }}

    <tr>
      <th>&nbsp;</th>
      <td><input type="submit" value="Enviar contato"/></td>
    </tr>
  </table>
</form>
{% endblock conteudo %}

meu_blog/templates/rodape.html
<div class="rodape">
Obrigado pela visita, volte sempre!
</div>

tags/templates/tags/tag.html
{% extends "base.html" %}

{% block titulo %}Tag "{{ tag.nome }}" - {{ block.super }}{% endblock %}

{% block h1 %}Tag "{{ tag.nome }}"{% endblock %}

{% block conteudo %}

<ul>
    {% for item in tag.tagitem_set.all %}
    <li><a href="{{ item.objeto.get_absolute_url }}">{{ item.objeto }}</a></li>
    {% endfor %}
</ul>

{% endblock conteudo %}

tags/templates/tags/tags.html
{% extends "base.html" %}

{% block titulo %}Tags - {{ block.super }}{% endblock %}

{% block h1 %}Tags{% endblock %}

{% block conteudo %}

<ul>
    {% for tag in lista %}
    <li><a href="{{ tag.get_absolute_url }}">{{ tag }}</a></li>
    {% endfor %}
</ul>

{% endblock conteudo %}

tags/templates/tags/tags_para_objeto.html
{% load tags_tags %}

<p>
Tags:
{% for tag in objeto|tags_para_objeto %}
<a href="{{ tag.get_absolute_url  }}">{{ tag }}</a>
{% endfor %}
</p>